# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Mind Ramblings
tagline:             'My Blog'
description:         'A Blog by my <em>mind</em>. <em>The Mind</em> is truely an intriguing place. It has a mind of its own.'
url:                 http://abinashmeher999.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Abinash Meher
  url:               https://github.com/abinashmeher999
  email:             abinashdakshana999@gmail.com

#jekyll-tagging
tag_page_layout: tag_page
tag_page_dir: tag

tag_feed_layout: tag_feed
tag_feed_dir: tag

tag_permalink_style: pretty
ignored_tags: []

# Custom vars
version:             1.0.0
