source 'https://rubygems.org'

gem 'jekyll'
gem 'pygments.rb','~> 0.6.0'
gem 'redcarpet','~> 3.1'
gem 'listen','~> 2.7'
gem 'jekyll-tagging'
gem 'jekyll-sitemap'
gem 'jekyll-mentions'
gem 'jemoji'
gem 'jekyll-redirect-from'
